[package]
name = "bevy_framepace"
version = "0.17.0-rc.0"
edition = "2021"
resolver = "2"
description = "Frame pacing and frame limiting for Bevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/aevyrie/bevy_framepace"
documentation = "https://docs.rs/bevy_framepace"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_app = "0.14.0-rc.2"
bevy_ecs = "0.14.0-rc.2"
bevy_diagnostic = "0.14.0-rc.2"
bevy_log = "0.14.0-rc.2"
bevy_render = "0.14.0-rc.2"
bevy_reflect = "0.14.0-rc.2"
bevy_time = "0.14.0-rc.2"
bevy_utils = "0.14.0-rc.2"
bevy_window = "0.14.0-rc.2"
bevy_winit = "0.14.0-rc.2"
# Non-bevy
spin_sleep = "1.0"

[features]
default = ["framepace_debug", "bevy_winit/x11"]
framepace_debug = []

[dev-dependencies]
bevy = { version = "0.14.0-rc.2", default-features = false, features = [
    "bevy_gizmos",
    "bevy_text",
    "bevy_ui",
    "default_font",
    "multi_threaded",
    "x11",
    # The following should not be needed: https://github.com/bevyengine/bevy/issues/13571
    "ktx2",
    "zstd",
    "bevy_pbr",
] }

[[example]]
name = "demo"
path = "examples/demo.rs"
required-features = ["default"]

[[example]]
name = "minimal"
path = "examples/minimal.rs"
required-features = ["default"]
